version: "3"
services:
  squid-alpine-ssl:
    image: alatas/squid-alpine-ssl:latest
    environment:
      - CN=squid.local.lan
      - O=squid
      - OU=squid
      - C=UK
    ports:
      - "3128:3128"
      - "4128:4128"
    volumes:
      - ./log:/var/log/
      - ./conf/squid.conf:/etc/squid/squid.conf
      - ./cache:/var/cache
      - ./cert:/etc/squid-cert
    restart: always
